### ISSUE TITLE
AttributeError: module 'attr' has no attribute 's'

### ISSUE THREAD

**Issue by dhuckins** [dephell/dephell_shells#1]
ran
```shell
$ python3.7 -m pip install dephell[full]
$ dephell autocomplete
Traceback (most recent call last):
  File "/home/username/.local/bin/dephell", line 7, in <module>
    from dephell.cli import entrypoint
  File "/home/username/.local/lib/python3.7/site-packages/dephell/cli.py", line 9, in <module>
    from .commands import commands
  File "/home/username/.local/lib/python3.7/site-packages/dephell/commands/__init__.py", line 2, in <module>
    from .autocomplete import AutocompleteCommand
  File "/home/username/.local/lib/python3.7/site-packages/dephell/commands/autocomplete.py", line 8, in <module>
    from dephell_shells import Shells
  File "/home/username/.local/lib/python3.7/site-packages/dephell_shells/__init__.py", line 1, in <module>
    from ._manager import Shells
  File "/home/username/.local/lib/python3.7/site-packages/dephell_shells/_manager.py", line 12, in <module>
    from ._base import BaseShell
  File "/home/username/.local/lib/python3.7/site-packages/dephell_shells/_base.py", line 16, in <module>
    @attr.s()
AttributeError: module 'attr' has no attribute 's'
```
(my username substituted for privacy)

**Comment by orsinium** [comment]
Thank you for the issue :) Please, remove [attr](https://pypi.org/project/attr/) and install [attrs](https://pypi.org/project/attrs/):
```
pip uninstall attr
pip install --user attrs
```

Fixed in https://github.com/dephell/dephell_discover/pull/3, I just forgot to release it. Now everything works

**Comment by dhuckins** [comment]
@orsinium thanks!

**Comment by orsinium** [comment]
You're welcome. Feel free to open an issue for anything :)
